# Generated by Django 4.1.7 on 2023-03-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'inactive'), (1, 'pending'), (2, 'pay')], default=1),
        ),
    ]
