# Generated by Django 4.1.7 on 2023-03-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
